In [768]:
import pandas as pd
import numpy as np
#Import libraries

In [770]:
games = pd.read_csv("games.csv",index_col=0)
#Reads the games.csv file taken from the Kaggle dataset and assigns the index as the first column

In [771]:
games.head()
#allows us to view the first 5 rows of the table to give insight into the table

,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
game_id,,,,,,,,,,,,,,,,,,,,,
2321044,L1,2013,2. Matchday,2013-08-18,16,23,2,1,1.0,15.0,...,SIGNAL IDUNA PARK,80200.0,Peter Sippel,https://www.transfermarkt.co.uk/borussia-dortm...,4-2-3-1,4-3-2-1,Borussia Dortmund,Eintracht Braunschweig,2:1,domestic_league
2321060,L1,2013,3. Matchday,2013-08-25,23,24,0,2,18.0,11.0,...,EINTRACHT-Stadion,23325.0,Wolfgang Stark,https://www.transfermarkt.co.uk/eintracht-brau...,4-3-2-1,4-2-3-1,Eintracht Braunschweig,Eintracht Frankfurt,0:2,domestic_league
2321086,L1,2013,6. Matchday,2013-09-21,4,16,1,1,15.0,1.0,...,Max-Morlock-Stadion,50000.0,Knut Kircher,https://www.transfermarkt.co.uk/1-fc-nuremberg...,4-2-3-1,4-2-3-1,1.FC Nuremberg,Borussia Dortmund,1:1,domestic_league
2321152,L1,2013,11. Matchday,2013-11-02,44,33,0,2,7.0,6.0,...,Olympiastadion Berlin,69277.0,Günter Perl,https://www.transfermarkt.co.uk/hertha-bsc_fc-...,4-2-3-1,4-2-3-1,Hertha BSC,FC Schalke 04,0:2,domestic_league
2321205,L1,2013,17. Matchday,2013-12-21,41,39,2,3,14.0,9.0,...,Volksparkstadion,50000.0,Bastian Dankert,https://www.transfermarkt.co.uk/hamburger-sv_1...,4-2-3-1,4-4-2 Diamond,Hamburger SV,1.FSV Mainz 05,2:3,domestic_league

In [774]:
games.shape
#this shows the number of rows and the number of columns

(68499, 22)

In [776]:
games.dtypes
#allows us to understand what types of data are inside the dataset

competition_id             object
season                      int64
round                      object
date                       object
home_club_id                int64
away_club_id                int64
home_club_goals             int64
away_club_goals             int64
home_club_position        float64
away_club_position        float64
home_club_manager_name     object
away_club_manager_name     object
stadium                    object
attendance                float64
referee                    object
url                        object
home_club_formation        object
away_club_formation        object
home_club_name             object
away_club_name             object
aggregate                  object
competition_type           object
dtype: object

In [778]:
games["date"] = pd.to_datetime(games["date"])
#converts date into a date format

In [780]:
#The above table now correctly shows the "date" column in the correct format

In [782]:
games["home_club_name"].value_counts()
#lists the number of home games stored within the data set for each club

home_club_name
Real Madrid      342
FC Barcelona     338
Juventus FC      328
Chelsea FC       327
Sevilla FC       323
                ...
Adanaspor         17
Orduspor          17
Balikesirspor     17
Beerschot AC      15
RWD Molenbeek     15
Name: count, Length: 426, dtype: int64

In [784]:
#for our dataset we only want to show games from the premier league in order to do so we will need to filter by premier league teams and by domestic league games only

In [786]:
#next I will create predictors for our machine learning model

In [788]:
games["home_formation_code"] = games["home_club_formation"].astype("category").cat.codes
#creates a column which sets the home formation type as an integer so the algorithm can use it for predictions

In [790]:
games["away_formation_code"] = games["away_club_formation"].astype("category").cat.codes
#creates a column which sets the away formation type as an integer so the algorithm can use it for predictions

In [792]:
games["home_club_code"] = games["home_club_id"].astype("category").cat.codes
#creates a column which sets the home formation type as an integer so the algorithm can use it for predictions

In [794]:
games["away_club_code"] = games["away_club_id"].astype("category").cat.codes
#creates a column which sets the home formation type as an integer so the algorithm can use it for predictions

In [796]:
games["target"] = np.where(games["home_club_goals"] > games["away_club_goals"],1,0)
#creates a conditonal column using numpys built-in where function to be used as a target for the prediction model if 1 home win, else 0

In [798]:
games.dtypes

competition_id                    object
season                             int64
round                             object
date                      datetime64[ns]
home_club_id                       int64
away_club_id                       int64
home_club_goals                    int64
away_club_goals                    int64
home_club_position               float64
away_club_position               float64
home_club_manager_name            object
away_club_manager_name            object
stadium                           object
attendance                       float64
referee                           object
url                               object
home_club_formation               object
away_club_formation               object
home_club_name                    object
away_club_name                    object
aggregate                         object
competition_type                  object
home_formation_code                 int8
away_formation_code                 int8
home_club_code                     int16
away_club_code                     int16
target                             int32
dtype: object

In [800]:
from sklearn.ensemble import RandomForestClassifier
#imports model from sklearn that picks out non-linearities in the data

In [802]:
rf = RandomForestClassifier(n_estimators=500, min_samples_split=100, random_state=1)
#n_estimators= number of individual decision trees to be trained 
#min_samples_split= number of samples we have in the decision trees
#random_state = 1 if we run mulitple times data will now stay the same

In [804]:
train = games[games["date"] < '2019-01-01']
#this trains the model on the data before 2023

In [806]:
test = games[games["date"] > '2019-01-01']
#this test the model on the data after 2023

In [808]:
predictors = ["home_club_code","away_club_code","home_formation_code","away_formation_code"]
#selects the above columns to be used as predictors in our model

In [810]:
rf.fit(train[predictors], train["target"])
#trains the random forest model with the above predictors

RandomForestClassifier(min_samples_split=100, n_estimators=500, random_state=1)

In [811]:
preds = rf.predict(test[predictors])
#this passes in the test data and predictors

In [812]:
from sklearn.metrics import accuracy_score
#this imports an accuracy score metric from sklearn and will allow us to show what percentage of the time the prediction was accurate

In [813]:
acc = accuracy_score(test["target"], preds)
#this passes in our actuals and predictions

In [814]:
acc
#this shows how often the prediction is accurate

0.6089561960592738

In [822]:
combined = pd.DataFrame(dict(actual=test["target"], prediction=preds))
#created a DataFrame to compare our actuals and predictions

In [824]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"])
#cross reference table to show how often prediction matched the actual

prediction      0     1
actual
0           12107  4924
1            7083  6591

In [830]:
from sklearn.metrics import precision_score
#importing precision score to tell us where we predicted a win how often did we predict the target

In [832]:
precision_score(test["target"], preds)

0.5723838471558836

In [834]:
grouped_games = games.groupby("home_club_name")
#create a DataFrame for each team for our data

In [836]:
group = grouped_games.get_group("Tottenham Hotspur")
#looks specifically at the Tottenham Hotspur group

In [838]:
group

,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,...,away_club_formation,home_club_name,away_club_name,aggregate,competition_type,home_formation_code,away_formation_code,home_club_code,away_club_code,target
game_id,,,,,,,,,,,,,,,,,,,,,
2578253,GB1,2015,35. Matchday,2016-04-25,148,984,1,1,2.0,13.0,...,4-1-4-1,Tottenham Hotspur,West Bromwich Albion,1:1,domestic_league,26,24,105,318,0
2872453,GB1,2017,34. Matchday,2018-04-14,148,281,1,3,4.0,1.0,...,4-3-3 Attacking,Tottenham Hotspur,Manchester City,1:3,domestic_league,26,31,105,127,0
2486657,GB1,2014,19. Matchday,2014-12-28,148,985,0,0,7.0,3.0,...,3-1-4-2,Tottenham Hotspur,Manchester United,0:0,domestic_league,26,10,105,319,0
2578102,GB1,2015,21. Matchday,2016-01-13,148,1003,0,1,4.0,2.0,...,4-4-1-1,Tottenham Hotspur,Leicester City,0:1,domestic_league,26,33,105,329,0
3194823,GB1,2019,1. Matchday,2019-08-10,148,405,3,1,6.0,15.0,...,4-1-4-1,Tottenham Hotspur,Aston Villa,3:1,domestic_league,28,24,105,174,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872273,GB1,2017,16. Matchday,2017-12-09,148,512,5,1,6.0,15.0,...,5-4-1,Tottenham Hotspur,Stoke City,5:1,domestic_league,26,43,105,214,1
2262471,EL,2012,group J,2012-11-08,148,790,3,1,NaN,NaN,...,NaN,Tottenham Hotspur,NaN,3:1,international_cup,-1,-1,105,279,1
2917452,CL,2017,Group H,2017-12-06,148,2784,3,0,NaN,NaN,...,4-3-3 Attacking,Tottenham Hotspur,NaN,3:0,international_cup,31,31,105,576,1
3592240,GB1,2021,37. Matchday,2022-05-15,148,1132,1,0,4.0,17.0,...,5-3-2,Tottenham Hotspur,Burnley FC,1:0,domestic_league,43,42,105,394,1
3462274,EL,2020,group J,2020-10-22,148,413,3,0,NaN,NaN,...,3-4-3,Tottenham Hotspur,NaN,3:0,international_cup,26,16,105,178,1

In [844]:
def rolling_averages(group, cols, new_cols):
    #adds to the precision of our model taking into account rolling average
        group = group.sort_values("date")
    #sorts by date
        rolling_stats = group[cols].rolling(3, closed="left").mean()
    #takes the last 3 values and takes the mean
        group[new_cols] = rolling_stats
        group = group.dropna(subset=new_cols)
    #drops any missing values so that we don't get errors where datasubset is too small
        return group

In [884]:
cols = ["home_club_goals", "away_club_goals", "home_club_position", "away_club_position"]
new_cols = [f"{c}_rolling" for c in cols]
#takes the original column names and adds _rolling on the end to show they're rolling averages

In [886]:
new_cols

['home_club_goals_rolling',
 'away_club_goals_rolling',
 'home_club_position_rolling',
 'away_club_position_rolling']

In [890]:
rolling_averages(group, cols, new_cols)

,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,...,competition_type,home_formation_code,away_formation_code,home_club_code,away_club_code,target,home_club_goals_rolling,away_club_goals_rolling,home_club_position_rolling,away_club_position_rolling
game_id,,,,,,,,,,,,,,,,,,,,,
2225539,GB1,2012,10. Matchday,2012-11-03,148,1071,0,1,6.0,14.0,...,domestic_league,-1,-1,105,362,0,2.000000,1.666667,6.000000,12.000000
2262471,EL,2012,group J,2012-11-08,148,790,3,1,NaN,NaN,...,international_cup,-1,-1,105,279,1,1.333333,1.666667,5.333333,10.333333
2285321,FAC,2012,Third Round,2013-01-05,148,990,3,0,NaN,NaN,...,domestic_cup,-1,-1,105,324,1,1.333333,0.333333,4.666667,12.666667
2225743,GB1,2012,38. Matchday,2013-05-19,148,289,1,0,5.0,17.0,...,domestic_league,-1,-1,105,129,1,2.000000,1.000000,4.666667,7.333333
2350374,GB1,2013,2. Matchday,2013-08-25,148,2288,1,0,2.0,20.0,...,domestic_league,32,32,105,499,1,1.666667,0.333333,5.000000,11.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4095379,GB1,2023,30. Matchday,2024-03-30,148,1031,2,1,5.0,18.0,...,domestic_league,26,31,105,340,1,2.000000,1.333333,4.666667,11.333333
4095398,GB1,2023,32. Matchday,2024-04-07,148,703,3,1,4.0,17.0,...,domestic_league,26,26,105,260,1,2.000000,1.333333,5.000000,14.333333
4095427,GB1,2023,35. Matchday,2024-04-28,148,11,2,3,5.0,2.0,...,domestic_league,26,31,105,8,0,2.666667,1.000000,4.666667,16.333333
4095448,GB1,2023,37. Matchday,2024-05-11,148,1132,2,1,5.0,19.0,...,domestic_league,31,34,105,394,1,2.333333,1.666667,4.666667,12.333333
4095418,GB1,2023,34. Matchday,2024-05-14,148,281,0,2,5.0,1.0,...,domestic_league,28,26,105,127,0,2.333333,1.666667,4.666667,12.666667

In [892]:
games_rolling = games.groupby("home_club_name").apply(lambda x: rolling_averages(x, cols, new_cols))
#applies the rolling averages to our original dataset

In [893]:
games_rolling

                             competition_id  season         round       date  \
home_club_name       game_id
1.FC Heidenheim 1846 4096037             L1    2023   8. Matchday 2023-10-22
                     4096055             L1    2023  10. Matchday 2023-11-05
                     4096074             L1    2023  12. Matchday 2023-11-26
                     4096092             L1    2023  14. Matchday 2023-12-09
                     4096110             L1    2023  16. Matchday 2023-12-20
...                                     ...     ...           ...        ...
Ümraniyespor         3860503            TR1    2022  27. Matchday 2023-04-02
                     3860444            TR1    2022  31. Matchday 2023-04-22
                     3860481            TR1    2022  33. Matchday 2023-05-07
                     3860518            TR1    2022  35. Matchday 2023-05-21
                     3860431            TR1    2022  37. Matchday 2023-06-03

                              home_club_id  away_club_id  home_club_goals  \
home_club_name       game_id
1.FC Heidenheim 1846 4096037          2036           167                2
                     4096055          2036            79                2
                     4096074          2036            80                0
                     4096092          2036           105                3
                     4096110          2036            60                3
...                                    ...           ...              ...
Ümraniyespor         3860503         24245          2293                2
                     3860444         24245           114                0
                     3860481         24245          2381                4
                     3860518         24245           868                1
                     3860431         24245         11688                0

                              away_club_goals  home_club_position  \
home_club_name       game_id
1.FC Heidenheim 1846 4096037                5                11.0
                     4096055                0                13.0
                     4096074                0                13.0
                     4096092                2                13.0
                     4096110                2                 9.0
...                                       ...                 ...
Ümraniyespor         3860503                2                18.0
                     3860444                2                18.0
                     3860481                1                17.0
                     3860518                2                17.0
                     3860431                1                17.0

                              away_club_position  ... competition_type  \
home_club_name       game_id                      ...
1.FC Heidenheim 1846 4096037                10.0  ...  domestic_league
                     4096055                 3.0  ...  domestic_league
                     4096074                14.0  ...  domestic_league
                     4096092                18.0  ...  domestic_league
                     4096110                 8.0  ...  domestic_league
...                                          ...  ...              ...
Ümraniyespor         3860503                 8.0  ...  domestic_league
                     3860444                 3.0  ...  domestic_league
                     3860481                11.0  ...  domestic_league
                     3860518                12.0  ...  domestic_league
                     3860431                16.0  ...  domestic_league

                             home_formation_code away_formation_code  \
home_club_name       game_id
1.FC Heidenheim 1846 4096037                  24                  36
                     4096055                  26                  26
                     4096074                  24                  31
                     4096092                  36                  14
                     4096110                  36                  36
...                                          ...                 ...
Ümraniyespor         3860503                  24                  26
                     3860444                  24                  26
                     3860481                  36                  24
                     3860518                  24                  16
                     3860431                  20                  26

                              home_club_code away_club_code target  \
home_club_name       game_id
1.FC Heidenheim 1846 4096037             551             85      0
                     4096055             551             48      1
                     4096074             551             49      0
                     4096092             551             57      1
                     4096110             551             41      1
...                                      ...            ...    ...
Ümraniyespor         3860503            1685            501      0
                     3860444            1685             59      0
                     3860481            1685            510      1
                     3860518            1685            295      0
                     3860431            1685           1202      0

                             home_club_goals_rolling away_club_goals_rolling  \
home_club_name       game_id
1.FC Heidenheim 1846 4096037                2.333333                1.666667
                     4096055                2.333333                2.333333
                     4096074                1.666667                1.666667
                     4096092                1.333333                1.666667
                     4096110                1.666667                0.666667
...                                              ...                     ...
Ümraniyespor         3860503                1.666667                1.000000
                     3860444                2.000000                1.000000
                     3860481                1.666667                1.333333
                     3860518                2.000000                1.666667
                     3860431                1.666667                1.666667

                             home_club_position_rolling  \
home_club_name       game_id
1.FC Heidenheim 1846 4096037                  12.333333
                     4096055                  10.666667
                     4096074                  11.333333
                     4096092                  12.333333
                     4096110                  13.000000
...                                                 ...
Ümraniyespor         3860503                  19.000000
                     3860444                  18.666667
                     3860481                  18.333333
                     3860518                  17.666667
                     3860431                  17.333333

                             away_club_position_rolling
home_club_name       game_id
1.FC Heidenheim 1846 4096037                  11.000000
                     4096055                  11.000000
                     4096074                   8.000000
                     4096092                   9.000000
                     4096110                  11.666667
...                                                 ...
Ümraniyespor         3860503                   6.333333
                     3860444                   8.333333
                     3860481                   7.666667
                     3860518                   7.333333
                     3860431                   8.666667

[35721 rows x 31 columns]

In [894]:
games_rolling = games_rolling.droplevel('home_club_name')
#this drops the home team name index level that was applied as it is not needed

In [895]:
games_rolling

,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,...,competition_type,home_formation_code,away_formation_code,home_club_code,away_club_code,target,home_club_goals_rolling,away_club_goals_rolling,home_club_position_rolling,away_club_position_rolling
game_id,,,,,,,,,,,,,,,,,,,,,
4096037,L1,2023,8. Matchday,2023-10-22,2036,167,2,5,11.0,10.0,...,domestic_league,24,36,551,85,0,2.333333,1.666667,12.333333,11.000000
4096055,L1,2023,10. Matchday,2023-11-05,2036,79,2,0,13.0,3.0,...,domestic_league,26,26,551,48,1,2.333333,2.333333,10.666667,11.000000
4096074,L1,2023,12. Matchday,2023-11-26,2036,80,0,0,13.0,14.0,...,domestic_league,24,31,551,49,0,1.666667,1.666667,11.333333,8.000000
4096092,L1,2023,14. Matchday,2023-12-09,2036,105,3,2,13.0,18.0,...,domestic_league,36,14,551,57,1,1.333333,1.666667,12.333333,9.000000
4096110,L1,2023,16. Matchday,2023-12-20,2036,60,3,2,9.0,8.0,...,domestic_league,36,36,551,41,1,1.666667,0.666667,13.000000,11.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3860503,TR1,2022,27. Matchday,2023-04-02,24245,2293,2,2,18.0,8.0,...,domestic_league,24,26,1685,501,0,1.666667,1.000000,19.000000,6.333333
3860444,TR1,2022,31. Matchday,2023-04-22,24245,114,0,2,18.0,3.0,...,domestic_league,24,26,1685,59,0,2.000000,1.000000,18.666667,8.333333
3860481,TR1,2022,33. Matchday,2023-05-07,24245,2381,4,1,17.0,11.0,...,domestic_league,36,24,1685,510,1,1.666667,1.333333,18.333333,7.666667
3860518,TR1,2022,35. Matchday,2023-05-21,24245,868,1,2,17.0,12.0,...,domestic_league,24,16,1685,295,0,2.000000,1.666667,17.666667,7.333333
3860431,TR1,2022,37. Matchday,2023-06-03,24245,11688,0,1,17.0,16.0,...,domestic_league,20,26,1685,1202,0,1.666667,1.666667,17.333333,8.666667

In [ ]:
def make_predictions(data, predictors):
    train = data[data["date"] <'2019-01-01']
    test = data[data["date"] > '2019-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, precision
    #the above combines our previous test and train set into one place making it easier to repeat the test following any changes

In [902]:
combined, precision = make_predictions(games_rolling, predictors + new_cols)
#combines the original predictors with the new column to see how often the algorithm correctly predicts a home win

In [903]:
precision

0.6001664816870145

In [ ]:
#slight improvement on the precision score taking it above 60%

In [868]:
combined

         actual  predicted
game_id
3122479       1          0
4095983       0          0
4096001       1          0
4096019       1          0
4096037       0          0
...         ...        ...
3860503       0          0
3860444       0          0
3860481       1          0
3860518       0          0
3860431       0          0

[25309 rows x 2 columns]

In [906]:
combined = combined.merge(games_rolling[["date","home_club_name","away_club_name","aggregate"]], left_index=True, right_index=True)
#merges columns from combined and the game rolling table to better understand mispredictions.

In [908]:
combined

,actual,predicted,date,home_club_name,away_club_name,aggregate
game_id,,,,,,
4096037,0,0,2023-10-22,1.FC Heidenheim 1846,FC Augsburg,2:5
4096055,1,0,2023-11-05,1.FC Heidenheim 1846,VfB Stuttgart,2:0
4096074,0,0,2023-11-26,1.FC Heidenheim 1846,VfL Bochum,0:0
4096092,1,0,2023-12-09,1.FC Heidenheim 1846,SV Darmstadt 98,3:2
4096110,1,0,2023-12-20,1.FC Heidenheim 1846,SC Freiburg,3:2
...,...,...,...,...,...,...
3860503,0,0,2023-04-02,Ümraniyespor,Konyaspor,2:2
3860444,0,0,2023-04-22,Ümraniyespor,Besiktas JK,0:2
3860481,1,0,2023-05-07,Ümraniyespor,Sivasspor,4:1
3860518,0,0,2023-05-21,Ümraniyespor,MKE Ankaragücü,1:2
3860431,0,0,2023-06-03,Ümraniyespor,Giresunspor,0:1